name: app_kit
description: "Library for simplifying basic application settings."
version: 0.0.1
repository: https://github.com/BaoBab-800/App-Kit

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: